# Default values for aurum.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ghcr.io/finitum/aurum
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 8042

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

config:
  port: 8042


# Generate these using aurum's keygen tool (see documentation)
secrets:
  publicKey: "-----BEGIN PUBLIC KEY-----\nMCowBQYDK2VwAyEAEPITXm1epHiN5/Lo+Qb1bJXc35kXO4Ci6cQ7flxuZUU=\n-----END PUBLIC KEY-----\n"
  secretKey: "-----BEGIN ED25519 PRIVATE KEY-----\nMC4CAQAwBQYDK2VwBCIEIHsnOgNEH/EBN/exY26xwA+Z6x/Eef79igkIsVLY7KcX\n-----END ED25519 PRIVATE KEY-----\n"

# Dgraph's helm chart: https://github.com/dgraph-io/charts/blob/master/charts/dgraph/values.yaml
dgraph:
  alpha:
    configFile:
      config.hcl: |
        whitelist = "0.0.0.0/0"

    persistence:
      enabled: true
      # storageClass: "-"
      accessModes:
        - ReadWriteOnce
      size: 5Gi
      annotations: {}

  zero:
    persistence:
      enabled: true
      # storageClass: "-"
      accessModes:
        - ReadWriteOnce
      size: 5Gi

  persistence:
    enabled: true
    accessModes:
      - ReadWriteOnce
    size: 2Gi


