# Default values for aurum.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ghcr.io/finitum/aurum
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 8042

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

config:
  webAddress: 0.0.0.0:8042


# Generate these using aurum's keygen tool (see documentation)
secrets:
  publicKey: "LS0tLS1CRUdJqTiBQVUJMSUMgS0VZLS0tLS1cbk1Db3dCUVlESzJWd0F5RUFTQkpKbEhUSEJNZUlwczhCdVhHU3prSTYrWks3OHhBRW9FZTVxZmlLY3kwPVxuLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0tXG4K"
  secretKey: "LS0tLS1CRUdJTiBFRDI1NTE5IFBSSVZBVEUgS0VZLS0tLS1cbk1DNENBUUF3QlFZREsyVndCQ0lFSVA2Q2o2SENmbVBVRjFCS0ZRTitVMzltUnFsMjQ2NG9TUHk0aG1sbE9VTXBcbi0tLS0tRU5EIEVEMjU1MTkgUFJJVkFURSBLRVktLS0tLVxuCg=="

# Dgraph's helm chart: https://github.com/dgraph-io/charts/blob/master/charts/dgraph/values.yaml
#dgraph:


