apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aurum.fullname" . }}
data:
  SECRET_KEY: {{ required "Missing secret key (use aurum keygen)" .Values.secrets.secretKey | b64enc }}
  PUBLIC_KEY: {{ required "Missing public key (use aurum keygen)" .Values.secrets.publicKey | b64enc }}

  {{ if .Values.secrets.password }}
  ADMIN_PASSWORD: {{ .Values.secrets.password | b64enc }}
  {{ else }}
  ADMIN_PASSWORD: {{ randAlphaNum 24 | b64enc }}
  {{ end }}